version: '2'
services:
  itemapplication:
    build:
      context: ./
    image: item-docker-manual
    environment:
      spring.data.mongodb.host: mongo
      spring.data.mongodb.port: 27017
      spring.data.mongodb.database: itemizedBill
      SERVER_PORT: 8080
    depends_on: 
      - mongo
    links:
      - mongo
    tty: false
    ports:
      - 8080:8080
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/db
